FROM python:3.7-buster

WORKDIR '/project'

COPY . .

RUN set -ex \
    && pip install --upgrade pip setuptools wheel \
    && pip install -e . \
    && pip install -r resources/requirements.txt

CMD ["python", "./src/manage.py", "runserver", "0.0.0.0:8000"]
